import { useState, useEffect, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import Chat from "./components/chat/Chat";
import Dashboard from "./components/dashboard/Dashboard";
import { useChatStore } from "./store/chatStore";
import { useDashboardStore } from "./store/dashboardStore";
import {
  ChatBubbleLeftRightIcon,
  SparklesIcon,
  ArrowUpTrayIcon,
  XMarkIcon,
} from "@heroicons/react/24/outline";

const API = "http://localhost:8000";

export default function App() {
  const [datasets, setDatasets] = useState([]);
  const [activeDataset, setActiveDataset] = useState(null);
  const [isChatOpen, setIsChatOpen] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [dashboardReadyMsg, setDashboardReadyMsg] = useState(false);
  const [activeQuarter, setActiveQuarter] = useState('All');
  const [activeCategory, setActiveCategory] = useState('All');
  const [detectedQuarter, setDetectedQuarter] = useState(null);

  const {
    conversations,
    activeConversation,
    createConversation,
    setActiveConversation,
  } = useChatStore();

  useEffect(() => {
    fetchDatasets();
  }, []);

  // ── Quarter detector (mirrors backend logic) ─────────────────────────────
  const detectQuarterFromFilename = (filename) => {
    const name = filename.toLowerCase();
    // Q12 → Q1 (longest first to avoid q1 matching q12)
    for (let i = 12; i >= 1; i--) {
      if (name.includes(`q${i}`)) return `Q${i}`;
    }
    // FY99 → FY25 (4-digit form first)
    for (let yr = 99; yr >= 25; yr--) {
      if (name.includes(`fy20${String(yr).padStart(2,'0')}`)) return `FY${yr}`;
      if (name.includes(`fy${yr}`)) return `FY${yr}`;
    }
    return null;
  };

  const autoGenerateDashboard = async (filename) => {
    // Legacy: just trigger a loading toast — Dashboard.jsx handles its own fetch
    setUploading(true);
    setDashboardReadyMsg(true);
    setTimeout(() => {
      setUploading(false);
      setDashboardReadyMsg(false);
    }, 3500);
  };

  const fetchDatasets = async () => {
    try {
      const res = await fetch(`${API}/api/files`);
      const data = await res.json();
      const files = data.files || [];
      setDatasets(files);
      if (files.length > 0 && !activeDataset) {
        const first = files[0].name;
        setActiveDataset(first);
        const convId = createConversation(first);
        setActiveConversation(convId);
        autoGenerateDashboard(first);
      }
    } catch (err) {
      console.error("Failed to fetch datasets:", err);
    }
  };

  const handleFileUpload = async (event) => {
    const files = event.target.files;
    if (!files || files.length === 0) return;

    const formData = new FormData();
    for (const file of files) {
      formData.append("files", file);
    }

    try {
      setUploading(true);
      const res = await fetch(`${API}/api/upload`, {
        method: "POST",
        body: formData,
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.detail);

      const firstName = files[0].name;
      setActiveDataset(firstName);

      // Auto-detect quarter from filename and jump to that tab
      const q = detectQuarterFromFilename(firstName);
      if (q) {
        setActiveQuarter(q);
        setDetectedQuarter(q);          // tells Dashboard to switch tab
      } else {
        setDetectedQuarter('All');      // no quarter → show All
      }

      const convId = createConversation(firstName);
      setActiveConversation(convId);
      setUploading(false);
      setDashboardReadyMsg(true);
      setTimeout(() => setDashboardReadyMsg(false), 3000);
      fetchDatasets();
    } catch (err) {
      console.error("Upload error:", err);
      setUploading(false);
    }
    event.target.value = "";
  };

  const handleCreateConversation = useCallback(() => {
    if (activeDataset) {
      const convId = createConversation(activeDataset);
      setActiveConversation(convId);
      return convId;
    }
    return null;
  }, [activeDataset, createConversation, setActiveConversation]);

  return (
    <div style={{
      display: "flex",
      height: "100vh",
      background: "#0A0F2C",
      color: "white",
      overflow: "hidden",
      position: "relative",
    }}>
      {/* ── Main Dashboard Area ── */}
      <main style={{ flex: 1, display: "flex", flexDirection: "column", height: "100%", position: "relative" }}>

        {/* ── Top bar: Upload button + file tabs ── */}
        <div style={{
          position: "absolute",
          top: 18,
          left: 22,
          right: 22,
          zIndex: 20,
          display: "flex",
          gap: 12,
          alignItems: "center",
          justifyContent: "space-between",
        }}>
          <label className="flex items-center gap-2 px-4 py-2 bg-[#00D4FF] hover:bg-[#00b4db] text-[#0A0F2C] text-sm font-semibold rounded-lg cursor-pointer transition-colors shadow-[0_0_15px_rgba(0,212,255,0.3)]">
            <ArrowUpTrayIcon style={{ width: 17, height: 17, color: "#0A0F2C" }} />
            Upload CSV
            <input
              type="file"
              multiple
              accept=".csv,.xlsx,.xls"
              style={{ display: "none" }}
              onChange={handleFileUpload}
            />
          </label>

          {/* ── File tabs selector ── */}
          {datasets.length > 0 && (
            <div style={{
              display: "flex",
              gap: 8,
              overflowX: "auto",
              paddingBottom: 4,
              flex: 1,
            }}>
              {datasets.map((dataset) => {
                const fileName = typeof dataset === 'string' ? dataset : dataset.name;
                const isActive = fileName === activeDataset;
                return (
                  <button
                    key={fileName}
                    onClick={() => {
                      setActiveDataset(fileName);
                      const q = detectQuarterFromFilename(fileName);
                      if (q) {
                        setActiveQuarter(q);
                        setDetectedQuarter(q);
                      }
                      const convId = createConversation(fileName);
                      setActiveConversation(convId);
                    }}
                    style={{
                      padding: "6px 14px",
                      borderRadius: 6,
                      fontSize: 11,
                      fontWeight: 600,
                      whiteSpace: "nowrap",
                      border: isActive ? `2px solid #00D4FF` : `1px solid rgba(255,255,255,0.2)`,
                      background: isActive ? "rgba(0,212,255,0.15)" : "rgba(255,255,255,0.05)",
                      color: isActive ? "#00D4FF" : "rgba(255,255,255,0.65)",
                      cursor: "pointer",
                      transition: "all 0.2s",
                    }}
                    onMouseOver={(e) => {
                      if (!isActive) {
                        e.target.style.background = "rgba(255,255,255,0.08)";
                        e.target.style.borderColor = "rgba(0,212,255,0.4)";
                      }
                    }}
                    onMouseOut={(e) => {
                      if (!isActive) {
                        e.target.style.background = "rgba(255,255,255,0.05)";
                        e.target.style.borderColor = "rgba(255,255,255,0.2)";
                      }
                    }}
                  >
                    📄 {fileName}
                  </button>
                );
              })}
            </div>
          )}
        </div>

        {uploading && (
          <div style={{
            position: "absolute",
            inset: 0,
            zIndex: 40,
            background: "rgba(10,10,10,0.88)",
            backdropFilter: "blur(6px)",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            gap: 18,
          }}>
            <motion.div
              animate={{ rotate: 360 }}
              transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
              className="w-16 h-16 border-4 border-[rgba(0,212,255,0.2)] border-t-[#00D4FF] rounded-full mx-auto mb-4"
            />
            <h2 style={{
              fontSize: 22,
              fontWeight: 700,
              color: "#ffffff",
              margin: 0,
              textShadow: "0 0 12px #00D4FF",
            }}>
              Generating Dashboard…
            </h2>
            <p style={{ color: "rgba(255,255,255,0.45)", margin: 0, fontSize: 13 }}>
              Analysing columns and building charts
            </p>
          </div>
        )}

        <AnimatePresence>
          {dashboardReadyMsg && (
            <motion.div
              initial={{ opacity: 0, y: -50 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -50 }}
              style={{
                position: "absolute",
                top: 20,
                left: "50%",
                transform: "translateX(-50%)",
                zIndex: 50,
                background: "#00D4FF",
                color: "#0A0F2C",
                padding: "8px 24px",
                borderRadius: 999,
                fontWeight: 800,
                fontSize: 14,
                boxShadow: "0 0 24px rgba(0,212,255,0.6)",
                whiteSpace: "nowrap",
              }}
            >
              ✓ Dashboard Ready!
            </motion.div>
          )}
        </AnimatePresence>

        <div style={{ flex: 1, overflow: "hidden", paddingTop: 64 }}>
          <Dashboard
            activeDataset={activeDataset}
            allDatasets={datasets}
            detectedQuarter={detectedQuarter}
            onQuarterChange={(q) => setActiveQuarter(q)}
          />
        </div>
      </main>

      <motion.button
        whileHover={{ scale: 1.12 }}
        whileTap={{ scale: 0.92 }}
        onClick={() => setIsChatOpen(true)}
        className="w-14 h-14 bg-[#00D4FF] border border-[#00b4db] text-[#0A0F2C] rounded-full shadow-[0_0_20px_rgba(0,212,255,0.4)] flex items-center justify-center hover:scale-105 transition-transform"
        style={{
          position: "fixed",
          bottom: 28,
          right: 28,
          zIndex: 40,
          cursor: "pointer",
        }}
        title="Open AI Chat"
      >
        <ChatBubbleLeftRightIcon style={{ width: 26, height: 26 }} />
      </motion.button>

      <AnimatePresence>
        {isChatOpen && (
          <>
            <motion.div
              key="backdrop"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              onClick={() => setIsChatOpen(false)}
              style={{
                position: "fixed",
                inset: 0,
                background: "rgba(0,0,0,0.55)",
                zIndex: 40,
                backdropFilter: "blur(3px)",
              }}
            />

            <motion.div
              key="panel"
              initial={{ x: "100%" }}
              animate={{ x: 0 }}
              exit={{ x: "100%" }}
              transition={{ type: "spring", damping: 26, stiffness: 200 }}
              className="h-full bg-[#0A0F2C] border-l border-[rgba(0,212,255,0.3)] shadow-[-10px_0_30px_rgba(0,0,0,0.5)] flex flex-col relative z-50"
              style={{
                position: "fixed",
                top: 0,
                right: 0,
                bottom: 0,
                width: 400,
                paddingTop: 48,
              }}
            >
              <button
                onClick={() => setIsChatOpen(false)}
                title="Close chat"
                className="p-1.5 rounded-md hover:bg-[rgba(0,212,255,0.1)] text-slate-400 hover:text-[#00D4FF] transition-colors"
                style={{
                  position: "absolute",
                  top: 12,
                  left: 14,
                  background: "transparent",
                  border: "none",
                  cursor: "pointer",
                  borderRadius: 6,
                  display: "flex",
                  alignItems: "center",
                }}
              >
                <XMarkIcon style={{ width: 20, height: 20 }} />
              </button>

              {/* Panel header */}
              <div style={{
                position: "absolute",
                top: 0,
                left: 0,
                right: 0,
                height: 48,
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                borderBottom: "1px solid rgba(0,212,255,0.15)",
                fontSize: 13,
                fontWeight: 700,
                color: "#00D4FF",
                letterSpacing: 1,
              }}>
                AI Chat Assistant
              </div>

              <div style={{ flex: 1, overflow: "hidden" }}>
                <Chat
                  activeDataset={activeDataset}
                  activeConversation={activeConversation}
                  onCreateConversation={handleCreateConversation}
                  activeQuarter={activeQuarter}
                  activeCategory={activeCategory}
                />
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </div>
  );
}
